# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Swedish Work Lab
email: contact@swedishworklab.com
description: Will you help us shape the future of work?
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.swedishworklab.com" # the base hostname & protocol for your site, e.g. http://example.com


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

collections:
  pageCollection:
    output: true
    permalink: /:name/
  projections:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:categories/:year/:month/:day/:title/


# defaults:
#   - scope:
#       path: ""
#       type: "hackathon"
#     values:
#       layout: "page"

# Site variables
image_path: assets/media
uploads_path: assets/media/uploads
js_path: assets/js
css_path: assets/css
fonts_path: assets/fonts
icons_path: assets/icons

# Site settings
show_excerpts: true

logo:
  two:
    white: /assets/media/SWL-LOGO-LOWER-WHITE.svg
    black: /assets/media/SWL-LOGO-LOWER-BLACK.svg
  three:
    white: /assets/media/SWL-LOGO-3-LOWER-WHITE.svg
    black: /assets/media/SWL-LOGO-3-LOWER-BLACK.svg
    black_animation: /assets/media/SWL-LOGO-3-LOWER-BLACK-ANIMATION.svg
    white_animation: /assets/media/SWL-LOGO-3-LOWER-WHITE-ANIMATION.svg

# Scripts
body_scripts:
  - /assets/js/jquery.min.js
  - /assets/js/jquery-color.min.js
  - /assets/js/utils.js
  - /assets/js/perlin.js
  - //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  - //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  - /assets/js/paper-full.min.js
  - /assets/js/barba.min.js
  - /assets/js/main.js

animation_scripts:
  - /assets/js/Tween.js
  - /assets/js/three.min.js
  - /assets/js/Projector.js
  - /assets/js/CanvasRenderer.js
  - /assets/js/CCapture.all.min.js
  # - /assets/js/STLExporter.js
  - /assets/js/OrbitControls.js
  - /assets/js/TrackballControls.js
  - /assets/js/OBJLoader.js
  - /assets/js/lab-canvas.js
  - /assets/js/blobs-canvas.js
  - /assets/js/canvas.js


fonts:
  - //fonts.googleapis.com/css?family=Open+Sans&display=swap
  - //fonts.googleapis.com/css?family=Roboto+Mono&display=swap
  - //fonts.googleapis.com/css?family=Source+Sans+Pro&display=swap
  - //fonts.googleapis.com/css?family=Lato&display=swap
  - //fonts.googleapis.com/css?family=Roboto&display=swap
  - //fonts.googleapis.com/css?family=Work+Sans&display=swap


plugins:
  - jekyll-target-blank
  - jekyll-minifier

google_analytics: 'UA-141826971-1'

sass:
    style: compressed

jekyll-minifier:
    preserve_php: false
    remove_spaces_inside_tags: true
    remove_multi_spaces: true
    remove_comments: true
    remove_intertag_spaces: true
    compress_css: false
    compress_javascript: true
    compress_json: true
    preserve_line_breaks: false
    uglifier_args:
      harmony: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - hackathon.md
  - lab.md
  - about.md
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
