# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Swedish Work Lab
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Will you help us shape the future of work?
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# social links
twitter_username: jekyllrb
github_username:  jekyll
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com



# Scripts

body_scripts:
  - //code.jquery.com/jquery-3.2.1.min.js
  - //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  - //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  - /assets/js/barba.min.js

animation_scripts:
  - /assets/js/Tween.js
  - /assets/js/three.min.js
  - /assets/js/Projector.js
  - /assets/js/CanvasRenderer.js
  - /assets/js/OrbitControls.js
  - /assets/js/TrackballControls.js
  - /assets/js/OBJLoader.js
  - /assets/js/perlin.js




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
