url: >-
  https://docs.google.com/forms/d/e/1FAIpQLSd50bpVpuF_jxq0lo4-2G9ECP367AzDU18J5eTBA9s6eoj7WQ/formResponse
inputs:
  description:
    field-name: entry.352770521
    label: Short description
  details:
    - field-name: entry.1702488782
      label: Name
    - field-name: entry.725733046
      label: Role (at TRR)
    - field-name: entry.1229249418
      label: Email
    - field-name: entry.1478548788
      label: Phone
    - field-name: entry.38474988
      label: Image
  food:
    field-name: entry.1064293053
    label: Food
