description: >-
  Will you help us shape the future of work? Maecenas faucibus mollis interdum.
  Donec sed odio dui. Aenean lacinia bibendum nulla sed consectetur. Fusce
  dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut
  fermentum massa justo sit amet risus. Cras mattis consectetur purus sit amet
  fermentum.
form-id: application_form
url: >-
  //script.google.com/macros/s/AKfycbwXvhNxU0PEUwSqfuyiWHFQYEO_gvjNIZELalBjkHtIYYa_zFuG/exec
inputs:
  details:
    - label: Name
      name: name
      type: text
    - label: Role (at TRR)
      name: role
      type: text
    - label: Email
      name: email
      type: text
    - label: Phone
      name: phone
      type: text
    - label: Image
      name: image
      type: file
    - label: Description
      name: description
      type: textarea
    - label: Food
      name: food
      type: text
submission: 'Thank you, you will hear back from us as soon as possible!'
