headline: 'I want to take part in the hackathon:'
description: >-
  **Our first step towards the future...**


  On September 5th 2019 we will bring perspectives from multiple disciplines
  together for a one day hackathon, to explore and solve challenges facing the
  future workplace. We will bring together bright minds with first-hand
  experience of facilitating a smooth work life for others with experts from
  industries and areas either affecting or being affected by the changes we see
  throughout society. 


  Half of the participants will be future-work experts from within TRR, and the
  other half will be thinkers, knowers, and doers from outside of TRR. We're
  looking for people with curiosity and ideas about what the future of work
  could, or should, look like. 


  The ideas and prototypes will be communicated and shared with the public after
  the hackathon, and winning ideas will be awarded the opportunity to be part of
  TRR Labs’ Pilot program.
form-id: application_form
url: >-
  //script.google.com/macros/s/AKfycbwXvhNxU0PEUwSqfuyiWHFQYEO_gvjNIZELalBjkHtIYYa_zFuG/exec
inputs:
  details:
    - label: Full Name
      name: name
      required: true
      type: text
    - label: Job Title
      name: role
      required: true
      type: text
    - label: Company
      name: company
      required: true
      type: text
    - label: Email
      name: email
      required: true
      type: text
    - label: Phone
      name: phone
      required: true
      type: text
    - label: Profile Picture (min 600 px)
      name: image
      required: true
      type: file
    - label: >-
        Tell us a little about yourself and why you would like to be a part of
        the hackathon (max 600 chars)
      name: description
      required: true
      type: textarea
    - label: Any food allergies/preferences
      name: food
      required: false
      type: text
terms: >-
  Your personal information will be handled by [TRR](http://www.trr.se) &
  [Another Tomorrow](http://www.anothertomorrow.io) (facilitating partner for
  the Swedish Work Lab). 


  We will not share your contact information with any other parties. 


  We will contact you only with information regarding the Swedish Work Lab and
  the hackathon. 


  By applying you consent to letting us use your name, your submitted image, and
  the description of you and why you would like to participate in Swedish Work
  Lab marketing material as well as participant presentations on this site. We
  will only use it in this way if you are selected to take part in the
  hackathon.


  Beyond this, your personal information will be maintained in accordance with
  GDPR and TRR’s standard practices. Read more
  [here](https://www.trr.se/om-trr/behandling-av-personuppgifter/) about how TRR
  handles personal information (in Swedish).
submission: >-
  Thank you for your application, you will hear back from us as soon as
  possible!
