headline: 'Apply to take part in the hackathon:'
description: >-
  Our first step towards the future...


  On September 5th 2019 we will bring perspectives from multiple disciplines
  together for a one day hackathon, to explore and solve challenges facing the
  future workplace. We will bring together bright minds with first-hand
  experience of facilitating a smooth work life for others with experts from
  industries and areas either affecting or being affected by the changes we see.
form-id: application_form
url: >-
  //script.google.com/macros/s/AKfycbwXvhNxU0PEUwSqfuyiWHFQYEO_gvjNIZELalBjkHtIYYa_zFuG/exec
inputs:
  details:
    - label: Name
      name: name
      type: text
    - label: Role (at TRR)
      name: role
      type: text
    - label: Email
      name: email
      type: text
    - label: Phone
      name: phone
      type: text
    - label: Image
      name: image
      type: file
    - label: Description
      name: description
      type: textarea
    - label: Food
      name: food
      type: text
submission: 'Thank you, you will hear back from us as soon as possible!'
