backend:
  name: git-gateway
  branch: master # Branch to update (master by default)

publish_mode: editorial_workflow

media_folder: "assets/media/uploads" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts (Not in use)" # Used in the UI, ie.: "New Post"
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    description: "Collection for the future possibility of having a posts section (currently not used)"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
    meta: # Meta data fields. Just like fields, but without any preview element
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
  - name: 'pages'
    label: 'Pages (Not in use)'
    description: "Collection for the future possibility of having different pages (currently not used)"
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'content'
    label: 'Content'
    description: "Collection for editing different types of content."
    files:
      - label: 'Content'
        name: 'content'
        file: '_data/content.yml'
        fields:
          - label: 'Site'
            name: 'site'
            widget: 'object'
            fields:
              - label: 'Title'
                name: 'title'
                widget: 'string'
                hint: 'Main title used across the site.'
              - label: 'Tag-line'
                name: 'tagline'
                widget: 'markdown'
                hint: 'Short description.'
                buttons:
                  - "italic"
                  - "link"
                  - "bold"
          - label: 'Intro'
            name: 'intro'
            widget: 'object'
            fields:
              - label: 'Headline'
                name: 'headline'
                widget: 'string'
              - label: 'Introduction'
                name: 'abstract'
                widget: 'markdown'
                hint: 'A description for the landing page'
                buttons:
                  - "italic"
                  - "link"
      - label: 'Event info'
        name: 'info'
        file: '_data/info.yml'
        fields:
          - label: 'Where'
            name: 'location'
            widget: 'object'
            fields:
              - label: 'Venue'
                name: 'venue'
                widget: 'object'
                fields:
                  - label: "Name"
                    name: "name"
                    widget: 'string'
                  - label: "URL"
                    name: "url"
                    widget: 'string'
              - label: 'Street address'
                name: 'street_address'
                widget: 'string'
              - label: 'Postal code'
                name: 'postal_code'
                widget: 'string'
              - label: "City"
                name: "city"
                widget: "string"
              - label: "Country"
                name: "country"
                widget: "string"
          - label: 'When'
            name: 'time'
            widget: "datetime"
          - label: "Contact"
            name: "contact"
            widget: 'string'
      - label: 'Application form'
        name: 'inputs'
        file: '_data/application-form.yml'
        fields:
          - label: "Description"
            name: "description"
            widget: "markdown"
            buttons:
              - "italic"
              - "link"
              - "bold"
            hint: "An description of the form."
          - label: "Form id"
            name: "form-id"
            widget: "hidden"
            default: "application_form"
          - label: 'Form url'
            name: "url"
            widget: "string"
            hint: 'Form action URL found in original Google Form source code.'
          - label: "Inputs"
            name: "inputs"
            widget: "object"
            fields:
              - label: 'Personal details'
                name: 'details'
                widget: 'list'
                fields:
                  - label: 'Input Label'
                    name: 'label'
                    widget: 'string'
                  - label: "Google Forms field name"
                    name: "field-name"
                    widget: "string"
                    hint: "Found in original Google Form source code."
                  - label: "Type"
                    name: "type"
                    widget: "select"
                    hint: "'text' for short text inputs and 'textarea' for longer, File/Image for image."
                    options:
                      - { label: "Short text", value: "text" }
                      - { label: "Long text", value: "textarea" }
                      - { label: "File/Image", value: "file" }
          - label: "Submission message"
            name: "submission"
            widget: "text"
            default: "Thank you!"
            hint: "Message showed when the user has submitted their form."
